apiVersion: apps/v1
kind: Deployment
metadata:
  name: wait-approval
  labels:
    app: wait-approval
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wait-approval
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: wait-approval
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: argoproj/rollouts-demo:yellow
        args:
          - server
        ports:
        - containerPort: 8080
